<?php

return [
    'assignments' => [
        'Knight8264' => ['Fabula Ultima'],
        'Dwarf5835' => ['Blades In The Dark', 'Call Of Cthulhu'],
        'Elf7755' => ['Fabula Ultima'],
        'Hunter5578' => ['Blades In The Dark'],
        'Shadow2193' => ['Blades In The Dark', 'Fabula Ultima'],
        'Wizard7554' => ['Pathfinder', 'Root RPG'],
        'MysticRaven' => ['Fabula Ultima', 'Dungeons & Dragons'],
        'DragonHeart' => ['Blades In The Dark'],
        'FrostGiant' => ['Vampire: The Masquerade'],
        'ThornSorcerer' => ['Shadowrun'],
        'Rogue4037' => ['Dungeons & Dragons'],
        'StarGazer' => ['Fabula Ultima'],
        'GoblinKing' => ['Pathfinder', 'Apocalypse World'],
        'WarriorOfTheSun' => ['Vampire: The Masquerade', 'Call Of Cthulhu'],
        'SilverSerpent' => ['Blades In The Dark', 'Call Of Cthulhu'],
        'EmberKnight' => ['Blades In The Dark', 'Vampire: The Masquerade'],
        'ShadowWeaver' => ['Fabula Ultima', 'Call Of Cthulhu'],
        'RuneSmith' => ['Dungeons & Dragons', 'Shadowrun'],
        'IronGolem' => ['Pathfinder'],
        'MoonlitFae' => ['Fabula Ultima'],
        'MoonBlessed' => ['Dungeons & Dragons'],
        'FireStarter' => ['Dungeons & Dragons'],
        'IceWarden' => ['Dungeons & Dragons'],
        'StormCaller' => ['Dungeons & Dragons'],
        'EarthShaker' => ['Dungeons & Dragons'],
        'LightBringer' => ['Dungeons & Dragons'],
        'DarkSayer' => ['Dungeons & Dragons'],
        'SkyWatcher' => ['Dungeons & Dragons'],
        'StarGazer' => ['Dungeons & Dragons'],
        'AbyssWatcher' => ['Dungeons & Dragons'],
        'FlameKeeper' => ['Dungeons & Dragons'],
        'VoidWalker' => ['Dungeons & Dragons'],
        'CelestialSage' => ['Dungeons & Dragons'],
        'FrostBinder' => ['Dungeons & Dragons'],
        'ThunderReign' => ['Dungeons & Dragons'],
        'EclipseSeer' => ['Dungeons & Dragons'],
        'NetherWhisper' => ['Dungeons & Dragons'],
        'SolarFlare' => ['Dungeons & Dragons'],
        'MysticWarden' => ['Dungeons & Dragons'],
        'ArcaneMaster' => ['Dungeons & Dragons'],
        'DawnRider' => ['Dungeons & Dragons'],
        'NightWhisper' => ['Dungeons & Dragons'],
        'SilverVeil' => ['Dungeons & Dragons'],
        'CrimsonBlade' => ['Dungeons & Dragons'],
        'ShadowMeld' => ['Dungeons & Dragons'],
        'DragonHeart' => ['Dungeons & Dragons'],
        'PhoenixRise' => ['Dungeons & Dragons'],
        'GaleForce' => ['Dungeons & Dragons'],
        'TideCaller' => ['Dungeons & Dragons'],
        'LunarMystic' => ['Dungeons & Dragons'],
    ],
];
