<?php

return [
  [
    "name" => "Knight8264",
    "email" => "knight826451@yahoo.com",
    "password" => "epSFEyjRvkzI",
    "role" => "game_master",
    "location" => "Milano",
    "game_description" => "Lost city awakens beneath modern metropolis, blending ancient magic and urban intrigue. Heroes navigate both worlds to prevent a cataclysm.",
    "max_players" => 4,
  ],
  [
    "name" => "Dwarf5835",
    "email" => "dwarf583540@yahoo.com",
    "password" => "qzzrPNINWbPJ",
    "role" => "game_master",
    "location" => "Roma",
    "game_description" => "Ancient dragons return to claim the world, heroes chosen by fate to find legendary weapons and restore balance.",
    "max_players" => 4,
  ],
  [
    "name" => "Elf7755",
    "email" => "elf775562@hotmail.com",
    "password" => "JUPJqMPSZItA",
    "role" => "game_master",
    "location" => "Torino",
    "game_description" => "A dark forest expands, swallowing lands; adventurers seek the heart-tree to reverse the curse, facing its guardians.",
    "max_players" => 4,
  ],
  [
    "name" => "Hunter5578",
    "email" => "hunter557836@yahoo.com",
    "password" => "BjORIwtJDkzD",
    "role" => "game_master",
    "location" => "Napoli",
    "game_description" => "A floating island appears, teeming with forgotten magic and technology. Parties race to uncover its secrets first.",
    "max_players" => 5,
  ],
  [
    "name" => "Shadow2193",
    "email" => "shadow219368@hotmail.com",
    "password" => "jfgThwKbPPpx",
    "role" => "game_master",
    "location" => "Sassari",
    "game_description" => "Undersea kingdoms face peril as a rift to a monstrous realm opens. Surface and sea heroes must unite.",
    "max_players" => 5,
  ],
  [
    "name" => "Wizard7554",
    "email" => "wizard755450@yahoo.com",
    "password" => "JHELRWDRDlDS",
    "role" => "game_master",
    "location" => "Pavia",
    "game_description" => "A celestial event grants powers to random beings. Heroes investigate the source, facing those who misuse their new gifts.",
    "max_players" => 3,
  ],
  [
    "name" => "MysticRaven",
    "email" => "MysticRaven@yahoo.com",
    "password" => "ACAeSqZjruWO",
    "role" => "game_master",
    "location" => "Livorno",
    "game_description" => "An eternal winter threatens to engulf the realm. Heroes quest for the Sun's Chalice to bring back spring.",
    "max_players" => 4,
  ],
  [
    "name" => "DragonHeart",
    "email" => "DragonHeart@gmail.com",
    "password" => "ZJGpUrOaBCyi",
    "role" => "game_master",
    "location" => "Latina",
    "game_description" => "Time fractures, merging past, present, and future. Heroes must navigate time-warped lands to repair the timeline.",
    "max_players" => 4,
  ],
  [
    "name" => "FrostGiant",
    "email" => "FrostGiant@hotmail.com",
    "password" => "UvHUifZsxMjf",
    "role" => "game_master",
    "location" => "Piacenza",
    "game_description" => "A hidden continent emerges, filled with ancient beasts and lost magic. Explorers face a land that time forgot.",
    "max_players" => 3,
  ],
  [
    "name" => "ThornSorcerer",
    "email" => "ThornSorcerer@hotmail.com",
    "password" => "TBTixbllFdKk",
    "role" => "game_master",
    "location" => "Catania",
    "game_description" => "A necromancer's curse raises the dead. Heroes journey to find the Amulet of Final Rest and end his reign.",
    "max_players" => 4,
  ],
  [
    "name" => "Rogue4037",
    "email" => "rogue40376@yahoo.com",
    "password" => "uIevnzosjhcH",
    "role" => "game_master",
    "location" => "Treviso",
    "game_description" => "An underground city of unspeakable wealth is discovered. Adventurers delve deep, facing greed and darkness to claim it.",
    "max_players" => 4,
  ],
  [
    "name" => "StarGazer",
    "email" => "StarGazer@gmail.com",
    "password" => "eswjFDLzHeYI",
    "role" => "game_master",
    "location" => "Rieti",
    "game_description" => "A god falls, scattering divine shards across the land. Mortals and immortals clash to gather them and ascend.",
    "max_players" => 6,
  ],
  [
    "name" => "GoblinKing",
    "email" => "GoblinKing@yahoo.com",
    "password" => "kfrpYKqeyWJR",
    "role" => "game_master",
    "location" => "Milano",
    "game_description" => "A massive labyrinth appears overnight, with promises of untold riches. Teams enter, but the maze changes with every dawn.",
    "max_players" => 4,
  ],
  [
    "name" => "WarriorOfTheSun",
    "email" => "WarriorOfTheSun@gmail.com",
    "password" => "iheayumyecXl",
    "role" => "game_master",
    "location" => "Roma",
    "game_description" => "A portal to another dimension opens, revealing a world opposite to ours. Heroes explore and face mirrored selves.",
    "max_players" => 5,
  ],
  [
    "name" => "SilverSerpent",
    "email" => "SilverSerpent@yahoo.com",
    "password" => "AKolNjjeGzww",
    "role" => "game_master",
    "location" => "Torino",
    "game_description" => "The moon cracks, revealing it was a prison for an ancient evil. Heroes race to prevent its escape.",
    "max_players" => 5,
  ],
  [
    "name" => "EmberKnight",
    "email" => "EmberKnight@hotmail.com",
    "password" => "CBTDjbOrEeYN",
    "role" => "game_master",
    "location" => "Napoli",
    "game_description" => "A kingdom lost to time resurfaces, but it’s cursed. Heroes must lift the curse before it spreads worldwide.",
    "max_players" => 4,
  ],
  [
    "name" => "ShadowWeaver",
    "email" => "ShadowWeaver@hotmail.com",
    "password" => "raPOpOUTJFct",
    "role" => "game_master",
    "location" => "Milano",
    "game_description" => "A legendary pirate’s map surfaces, leading to a ghostly fleet and the greatest treasure. A high seas adventure.",
    "max_players" => 5,
  ],
  [
    "name" => "RuneSmith",
    "email" => "RuneSmith@yahoo.com",
    "password" => "AAsYZyEVdxEf",
    "role" => "game_master",
    "location" => "Milano",
    "game_description" => "An ancient library is discovered, holding knowledge and secrets. Scholars and thieves alike vie for its treasures.",
    "max_players" => 4,
  ],
  [
    "name" => "IronGolem",
    "email" => "IronGolem@hotmail.com",
    "password" => "XsrEvpjPGHTg",
    "role" => "game_master",
    "location" => "Roma",
    "game_description" => "A world tree’s roots are dying, threatening all life. Heroes undertake a perilous journey to the underworld to save it.",
    "max_players" => 3,
  ],
  [
    "name" => "MoonlitFae",
    "email" => "MoonlitFae@gmail.com",
    "password" => "TnEotlSVGrMg",
    "role" => "game_master",
    "location" => "Roma",
    "game_description" => "A city’s dreams become reality, unleashing nightmares. Heroes must find and close the rift to the Dreamlands.",
    "max_players" => 4,
  ],
];